project:
  type: website
  output-dir: docs
  preview:
    port: 7777
    browser: false

website:
  title: "NASA Ocean AI Working Group"
  site-url: https://nasa-oceanai.github.io
  navbar:
    logo: logo.jfif
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Teams"
        href: teams.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Datasets"
        href: datasets.qmd
      - text: "Tools"
        href: tools.qmd  
      - text: "Events"
        href: events.qmd
      - text: "Community"
        href: community.qmd
      - text: "Contact"
        href: contact.qmd
    tools:
      - icon: github
        href: https://https://github.com/nasa-oceanaii
        text: NASA Ocean-AI GitHub
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo-dark, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
bibliography: references.bib
