name: Quarto Render and Deploy

on:
  push:
    branches:
      - main  # Change this if you use a different branch
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Quarto via Python
        run: |
          pip install quarto-cli
          quarto --version  # Verify installation

      - name: Render Quarto Project
        run: quarto render

      - name: Copy references.bib to docs/
        run: cp references.bib docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Quarto default output directory
